# Generated by Django 4.2.4 on 2025-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('case', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('username', models.CharField(default='default_user', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LoginView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
