# Generated by Django 4.2.4 on 2025-05-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryLine',
            new_name='InventoryCapture',
        ),
        migrations.RenameModel(
            old_name='LoginView',
            new_name='UserMaster',
        ),
    ]
