# Generated by Django 4.2.4 on 2025-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0002_rename_inventoryline_inventorycapture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextupNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Starting_Number', models.IntegerField(default=0)),
                ('Ending_Number', models.IntegerField(default=0)),
                ('Current_Number', models.IntegerField(default=0)),
                ('Next_Number', models.IntegerField(default=0)),
            ],
        ),
    ]
