# Generated by Django 4.2.4 on 2025-05-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0003_nextupnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextupnumber',
            name='Current_Number',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Ending_Number',
            field=models.CharField(default='ASN999999', max_length=100),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Next_Number',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Starting_Number',
            field=models.CharField(default='ASN000001', max_length=100),
        ),
    ]
