# Generated by Django 4.2.4 on 2025-05-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0004_alter_nextupnumber_current_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('case', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('asn_number', models.CharField(max_length=20)),
                ('line_number', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Current_Number',
            field=models.CharField(default='ASN000001', max_length=100),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Next_Number',
            field=models.CharField(default='ASN000002', max_length=100),
        ),
    ]
