# Generated by Django 4.2.4 on 2025-05-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0005_downloadinventory_alter_nextupnumber_current_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadinventory',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
