# Generated by Django 4.2.4 on 2025-05-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0006_downloadinventory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('case', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('asn_number', models.CharField(max_length=20)),
                ('line_number', models.CharField(max_length=6)),
            ],
        ),
    ]
