# Generated by Django 4.2.4 on 2025-05-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0007_inventoryline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryLine',
        ),
    ]
