# Generated by Django 4.2.4 on 2025-05-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0008_delete_inventoryline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadinventory',
            name='status',
        ),
    ]
