# Generated by Django 4.2.4 on 2025-05-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0009_remove_downloadinventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadinventory',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
