# Generated by Django 4.2.4 on 2025-05-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0011_nextupnumber_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextupnumber',
            name='prefix',
        ),
    ]
