# Generated by Django 4.2.4 on 2025-05-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0012_remove_nextupnumber_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextupnumber',
            name='prefix',
            field=models.CharField(default='ASN', max_length=10),
        ),
    ]
