# Generated by Django 4.2.4 on 2025-05-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0013_nextupnumber_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
