# Generated by Django 4.2.4 on 2025-05-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0014_usermaster_updated_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadinventory',
            name='download_status',
            field=models.CharField(default='No', max_length=5),
        ),
    ]
