# Generated by Django 4.2.4 on 2025-05-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0015_downloadinventory_download_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadinventory',
            name='download_status',
            field=models.CharField(max_length=5),
        ),
    ]
