# Generated by Django 4.2.4 on 2025-05-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0016_alter_downloadinventory_download_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadinventory',
            name='download_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
