# Generated by Django 4.2.4 on 2025-05-30 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0017_alter_downloadinventory_download_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextupnumber',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nextupnumber',
            name='created_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nextupnumber',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nextupnumber',
            name='updated_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Current_Number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Ending_Number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Next_Number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Starting_Number',
            field=models.CharField(max_length=50),
        ),
    ]
