# Generated by Django 4.2.4 on 2025-06-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0018_nextupnumber_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycapture',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
