# Generated by Django 4.2.4 on 2025-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0019_alter_inventorycapture_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycapture',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
