# Generated by Django 4.2.4 on 2025-06-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0020_alter_inventorycapture_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextupnumber',
            old_name='updated_date',
            new_name='updated_datetime',
        ),
    ]
