# Generated by Django 4.2.4 on 2025-06-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0021_rename_updated_date_nextupnumber_updated_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycapture',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
