# Generated by Django 4.2.4 on 2025-06-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0022_alter_inventorycapture_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextupnumber',
            old_name='prefix',
            new_name='type',
        ),
    ]
