# Generated by Django 4.2.4 on 2025-06-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0023_rename_prefix_nextupnumber_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextupnumber',
            old_name='type',
            new_name='prefix',
        ),
    ]
