# Generated by Django 4.2.4 on 2025-06-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0024_rename_type_nextupnumber_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextupnumber',
            name='max_records_per_asn',
            field=models.IntegerField(default=5),
        ),
    ]
