# Generated by Django 4.2.4 on 2025-06-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0025_nextupnumber_max_records_per_asn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextupnumber',
            old_name='max_records_per_asn',
            new_name='NUMBEROFLINES',
        ),
    ]
