# Generated by Django 4.2.4 on 2025-06-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0026_rename_max_records_per_asn_nextupnumber_numberoflines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextupnumber',
            old_name='NUMBEROFLINES',
            new_name='max_records_per_asn',
        ),
    ]
