# Generated by Django 4.2.4 on 2025-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0028_rename_max_records_per_asn_nextupnumber_numberoflines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextupnumber',
            name='NUMBEROFLINES',
            field=models.IntegerField(default=50),
        ),
    ]
