# Generated by Django 4.2.4 on 2025-06-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0029_alter_nextupnumber_numberoflines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextupnumber',
            name='NUMBEROFLINES',
            field=models.IntegerField(default=5),
        ),
    ]
