# Generated by Django 4.2.4 on 2025-06-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0030_alter_nextupnumber_numberoflines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorycapture',
            old_name='owner',
            new_name='OWNER',
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='NUMBEROFLINES',
            field=models.IntegerField(default=0),
        ),
    ]
