# Generated by Django 4.2.4 on 2025-06-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0031_rename_owner_inventorycapture_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorycapture',
            old_name='OWNER',
            new_name='owner',
        ),
    ]
