# Generated by Django 4.2.4 on 2025-06-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0033_rename_owner_inventorycapture_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorycapture',
            old_name='OWNER',
            new_name='owner',
        ),
    ]
