# Generated by Django 4.2.4 on 2025-06-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0034_rename_owner_inventorycapture_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadinventory',
            name='asn_number',
            field=models.CharField(db_column='ASNNUMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadinventory',
            name='case',
            field=models.CharField(db_column='CASE', max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadinventory',
            name='download_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], db_column='DOWNLOADSTATUS', default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='downloadinventory',
            name='line_number',
            field=models.CharField(db_column='LINENUMBER', max_length=6),
        ),
        migrations.AlterField(
            model_name='downloadinventory',
            name='location',
            field=models.CharField(db_column='LOCATION', max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadinventory',
            name='owner',
            field=models.CharField(db_column='OWNER', max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadinventory',
            name='quantity',
            field=models.IntegerField(db_column='QUANTITY', default=1),
        ),
        migrations.AlterField(
            model_name='downloadinventory',
            name='sku',
            field=models.CharField(db_column='SKU', max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadinventory',
            name='status',
            field=models.IntegerField(db_column='STATUS', default=1),
        ),
        migrations.AlterField(
            model_name='downloadinventory',
            name='uom',
            field=models.CharField(db_column='UOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorycapture',
            name='case',
            field=models.CharField(db_column='CASE', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorycapture',
            name='created_date',
            field=models.DateTimeField(blank=True, db_column='CREATEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='inventorycapture',
            name='location',
            field=models.CharField(db_column='LOCATION', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorycapture',
            name='owner',
            field=models.CharField(db_column='OWNER', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorycapture',
            name='quantity',
            field=models.IntegerField(db_column='QUANTITY', default=1),
        ),
        migrations.AlterField(
            model_name='inventorycapture',
            name='sku',
            field=models.CharField(db_column='SKU', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorycapture',
            name='status',
            field=models.IntegerField(db_column='STATUS', default=0),
        ),
        migrations.AlterField(
            model_name='inventorycapture',
            name='uom',
            field=models.CharField(db_column='UOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorycapture',
            name='username',
            field=models.CharField(db_column='USERNAME', default='default_user', max_length=100),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Current_Number',
            field=models.CharField(db_column='CURRENTNUMBER', max_length=50),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Ending_Number',
            field=models.CharField(db_column='ENDINGNUMBER', max_length=50),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='NUMBEROFLINES',
            field=models.IntegerField(db_column='NUMBEROFLINES', default=0),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Next_Number',
            field=models.CharField(db_column='NEXTNUMBER', max_length=50),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='Starting_Number',
            field=models.CharField(db_column='STARTINGNUMBER', max_length=50),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='created_date',
            field=models.DateTimeField(blank=True, db_column='CREATEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='created_username',
            field=models.CharField(blank=True, db_column='CREATEDUSERNAME', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='prefix',
            field=models.CharField(db_column='PREFIX', default='ASN', max_length=10),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, db_column='UPDATEDDATETIME', null=True),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='updated_username',
            field=models.CharField(blank=True, db_column='UPDATEDUSERNAME', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='created_date',
            field=models.DateTimeField(blank=True, db_column='CREATEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='password',
            field=models.CharField(db_column='PASSWORD', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, db_column='UPDATEDDATETIME', null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='username',
            field=models.CharField(db_column='USERNAME', max_length=100, unique=True),
        ),
    ]
