# Generated by Django 4.2.4 on 2025-06-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0035_alter_downloadinventory_asn_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycapture',
            name='created_date',
            field=models.DateTimeField(blank=True, db_column='ADDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='created_date',
            field=models.DateTimeField(blank=True, db_column='ADDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='prefix',
            field=models.CharField(db_column='TYPE', default='ASN', max_length=10),
        ),
        migrations.AlterField(
            model_name='nextupnumber',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, db_column='LASTLOGIN', null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='created_date',
            field=models.DateTimeField(blank=True, db_column='ADDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, db_column='LASTLOGIN', null=True),
        ),
    ]
