# Generated by Django 4.2.4 on 2025-06-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0036_alter_inventorycapture_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='downloadinventory',
            table='DOWNLOADINVENTORY',
        ),
        migrations.AlterModelTable(
            name='inventorycapture',
            table='INVENTORYCAPTURE',
        ),
        migrations.AlterModelTable(
            name='nextupnumber',
            table='NEXTUPNUMBER',
        ),
        migrations.AlterModelTable(
            name='usermaster',
            table='USERMASTER',
        ),
    ]
